import ComingSoon from 'components/ComingSoon';
import Head from 'next/head';

const comingSoon = true;

const Home = () =>
  comingSoon ? (
    <ComingSoon />
  ) : (
    <div>
      <Head>
        <title>YourMart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://yourmart.com">YourMart!</a>
        </h1>
      </main>
    </div>
  );

export default Home;
